import type { Mission } from "./types";

/**
 * Story Missions — the "Get Out There" engine.
 * Each mission nudges a user to go live something, then come back and write it.
 */
export const MISSIONS: Mission[] = [
  {
    id: "m-stranger",
    title: "Talk to a stranger",
    description:
      "Strike up a real conversation with someone you've never met. No phone in hand.",
    category: "Confession",
    difficulty: "easy",
    prompt: "What surprised you about them?",
    reward_badge: "mission-runner",
    accepted_count: 4210,
    completed_count: 1880,
    created_at: "2026-05-01T10:00:00Z",
  },
  {
    id: "m-alone",
    title: "Go somewhere alone",
    description: "A bar, a diner, a movie — go by yourself and sit with it.",
    category: "Travel",
    difficulty: "easy",
    prompt: "What did the silence tell you?",
    reward_badge: null,
    accepted_count: 3120,
    completed_count: 1402,
    created_at: "2026-05-03T10:00:00Z",
  },
  {
    id: "m-yes",
    title: "Say yes to something random",
    description: "The next invitation you'd normally decline — accept it.",
    category: "Wild Night",
    difficulty: "medium",
    prompt: "Where did 'yes' take you?",
    reward_badge: null,
    accepted_count: 2890,
    completed_count: 980,
    created_at: "2026-05-05T10:00:00Z",
  },
  {
    id: "m-craziest",
    title: "Ask someone their craziest story",
    description: "Then tell it here (with their blessing, names removed).",
    category: "Funny",
    difficulty: "easy",
    prompt: "What's the wildest thing you heard?",
    reward_badge: null,
    accepted_count: 2510,
    completed_count: 1120,
    created_at: "2026-05-07T10:00:00Z",
  },
  {
    id: "m-newbar",
    title: "Visit a bar you've never been to",
    description: "Somewhere outside your usual orbit. Watch. Listen. Report back.",
    category: "Nightlife",
    difficulty: "medium",
    prompt: "Who did you meet at the end of the bar?",
    reward_badge: "local-legend",
    accepted_count: 3340,
    completed_count: 1290,
    created_at: "2026-05-09T10:00:00Z",
  },
  {
    id: "m-call",
    title: "Call someone you miss",
    description: "Not text. Call. The person you keep meaning to.",
    category: "Relationships",
    difficulty: "bold",
    prompt: "What did you finally say?",
    reward_badge: null,
    accepted_count: 4980,
    completed_count: 2210,
    created_at: "2026-05-11T10:00:00Z",
  },
  {
    id: "m-scares",
    title: "Do something that scares you a little",
    description: "Small fear, real edge. Then write the moment before you did it.",
    category: "Comeback Story",
    difficulty: "bold",
    prompt: "What were you afraid of, really?",
    reward_badge: null,
    accepted_count: 3760,
    completed_count: 1540,
    created_at: "2026-05-13T10:00:00Z",
  },
  {
    id: "m-event",
    title: "Go to a local event and write what happened",
    description: "Open mic, market, protest, show. Be a witness for the night.",
    category: "Local",
    difficulty: "medium",
    prompt: "What did the crowd reveal?",
    reward_badge: "local-legend",
    accepted_count: 2150,
    completed_count: 870,
    created_at: "2026-05-15T10:00:00Z",
  },
  {
    id: "m-almostleft",
    title: "Write about the moment you almost left",
    description: "A job, a city, a person, a life. The fork you stared down.",
    category: "Regret",
    difficulty: "bold",
    prompt: "Why did you stay — or go?",
    reward_badge: null,
    accepted_count: 5120,
    completed_count: 2680,
    created_at: "2026-05-17T10:00:00Z",
  },
];

export function getMission(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}
